export const types = {
  FETCH_WEATHER_START : " FETCH_WEATHER_START",
  FETCH_WEATHER_SUCCESS : "FETCH_WEATHER_SUCCESS",
  FETCH_WEATHER_FAILURE : "FETCH_WEATHER_FAILURE",
  TOGGLE_METRIC : "TOGGLE_METRIC"


}